### PR TITLE
grouped natural conversion class and test and schema

### PR DESCRIPTION
**Pull request by augeorge**
added a class for GroupedNaturalConversion, a unit test, and an updated schema.

### CODE REVIEW

**Comment by augeorge** [comment]
see issue https://github.com/gyorilab/mira/issues/345

**Comment by bgyori** [comment]
Thanks, this looks good! I am still thinking about the right name for this, "Grouped" might not be the best choice for what this is, I'll think about an alternative. We will also look at other places in the package where the new template type would have to be handled.

**Comment by augeorge** [comment]
> Thanks, this looks good! I am still thinking about the right name for this, "Grouped" might not be the best choice for what this is, I'll think about an alternative. We will also look at other places in the package where the new template type would have to be handled.

thanks, I think the sbml processor should be updated as well
https://github.com/gyorilab/mira/blob/7d98f519f06a471284009b56e7af9b0d8f4201e9/mira/sources/sbml/processor.py#L300

**Comment by bgyori** [comment]
Hi @augeorge, just an update: thanks for starting the implementation. I made some local changes to naming, etc. and we started on supporting the kind of metabolic model you are working with. This, however, requires overcoming multiple complications such as (1) handling some SBML corner cases related to species annotation (2) handling reversible reactions (3) mapping non-trivial stoichiometry to the template representation. We are making progress and will try to finish these new features as soon as possible.

**Comment by bgyori** [comment]
It appears the box was not checked to allow maintainers to make changes to the PR so I will have to close this and open a new one with the new implementation.

**Pull request closed without merging**
